spring.application.name=pymez

# ===============================
# Configuración de la Base de Datos H2
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# Configuración de JPA / Hibernate
# ===============================
# create-drop: crea las tablas al iniciar y las borra al apagar (ideal para pruebas)
# update: actualiza el esquema sin borrar datos (útil si usas H2 en archivo físico)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# ===============================
# Consola Web de H2 (Muy recomendado)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console